//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationAndAuthorizationPart2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int CartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProductName { get; set; }
        public string Photo { get; set; }
        public Nullable<int> DiscountPrice { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
